import { Inbox, Search, Star, Trash2 } from "lucide-react";
import { Form, Link, useLoaderData } from "react-router";
import { loadMailbox } from "../lib/mail/mailbox-loader.server";
import { updateMailbox } from "../lib/mail/list-actions.server";
import { Shell } from "../components/shell";
import "../styles/mail-list-actions.css";

const formatDate = (date: string) => new Intl.DateTimeFormat("ja-JP", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(date));
export async function loader(args: { request: Request; context: ReadonlyMap<unknown, unknown> }) { return loadMailbox("inbox", args); }
export async function action(args: { request: Request; context: ReadonlyMap<unknown, unknown> }) { return updateMailbox("inbox", args); }
export default function Mailbox() { const { type, items } = useLoaderData<typeof loader>(), title = type === "inbox" ? "受信トレイ" : "送信済み"; return <Shell><section className="mail-list"><header className="list-header"><div><p className="eyebrow">{type.toUpperCase()}</p><h1>{title}</h1></div><span className="count-badge">{items.length}</span></header><div className="search"><Search size={17} /><input placeholder="メールを検索" /></div><div className="messages">{items.length ? items.map(mail => <article key={mail.id} className="message-row"><Link className="message-link" to={`/mails/${type}/${mail.id}`}><span className={mail.retained ? "star retained" : "star"}><Star size={16} fill={mail.retained ? "currentColor" : "none"} /></span><div className="message-content"><div><b>{mail.from}</b><time>{formatDate(mail.timestamp)}</time></div><strong>{mail.subject || "(件名なし)"}</strong><p>{mail.retained ? "保持中" : `期限: ${new Date(mail.expiresAt!).toLocaleDateString("ja-JP")}`}</p></div></Link><div className="message-actions"><Form method="post"><input type="hidden" name="id" value={mail.id} /><input type="hidden" name="intent" value={mail.retained ? "release" : "retain"} /><button className={mail.retained ? "icon-button kept" : "icon-button"} aria-label={mail.retained ? "保持を解除" : "保持する"} title={mail.retained ? "保持を解除" : "保持する"}><Star size={17} fill={mail.retained ? "currentColor" : "none"} /></button></Form><Form method="post" onSubmit={event => { if (!window.confirm("このメールを削除しますか？ この操作は取り消せません。")) event.preventDefault(); }}><input type="hidden" name="id" value={mail.id} /><input type="hidden" name="intent" value="delete" /><button className="icon-button" aria-label="メールを削除" title="メールを削除"><Trash2 size={17} /></button></Form></div></article>) : <div className="empty-state"><Inbox size={26} /><b>メールはありません</b><span>新しいメールが届くと、ここに表示されます。</span></div>}</div></section></Shell>; }
