import { ChevronLeft, Reply, Star, Trash2 } from "lucide-react";
import { Form, Link, redirect, useLoaderData } from "react-router";
import { MailStore } from "../lib/mail/store.server";
import type { MailType } from "../lib/mail/types";
import { mailTtl } from "../lib/mail/receiver.server";
import { getCloudflareContext } from "../lib/request-context.server";
import { requireSession } from "../lib/auth.server";
import { Shell } from "../components/shell";
import { MailContent } from "../components/mail-content";

function type(value: string | undefined): MailType | undefined { return value === "inbox" || value === "sent" ? value : undefined; }
function validId(value: string | undefined) { return !!value && /^[0-9A-HJKMNP-TV-Z]{26}$/i.test(value); }
export async function loader({ request, params, context }: { request: Request; params: Record<string, string | undefined>; context: ReadonlyMap<unknown, unknown> }) { const { env } = getCloudflareContext(context), direction = type(params.type), id = params.id; await requireSession(request, env); if (!direction || !validId(id)) throw new Response("Not found", { status: 404 }); const entry = await new MailStore(env.MAIL_KV).get(direction, id!); if (!entry.value || !entry.metadata) throw new Response("Not found", { status: 404 }); return { id: id!, type: direction, metadata: entry.metadata, raw: new TextDecoder().decode(entry.value) }; }
export async function action({ request, params, context }: { request: Request; params: Record<string, string | undefined>; context: ReadonlyMap<unknown, unknown> }) { const { env } = getCloudflareContext(context), direction = type(params.type), id = params.id; await requireSession(request, env); if (!direction || !validId(id)) throw new Response("Not found", { status: 404 }); const store = new MailStore(env.MAIL_KV), form = await request.formData(), intent = form.get("intent"); if (intent === "delete") { await store.delete(direction, id!); throw redirect(`/${direction}`); } if (intent === "release") await store.release(direction, id!, mailTtl(env)); else await store.retain(direction, id!); throw redirect(`/mails/${direction}/${id!}`); }
export default function MailDetail() { const { id, metadata, raw, type } = useLoaderData<typeof loader>(); return <Shell><section className="detail-panel"><header className="detail-toolbar"><Link className="icon-button" to={`/${type}`} aria-label="戻る"><ChevronLeft size={20} /></Link><div className="toolbar-actions">{type === "inbox" && <Link className="subtle-button" to={`/compose?reply=${type}&id=${id}`}><Reply size={16} />返信</Link>}<Form method="post"><input type="hidden" name="intent" value={metadata.retained ? "release" : "retain"} /><button className={metadata.retained ? "subtle-button kept" : "subtle-button"}><Star size={16} fill={metadata.retained ? "currentColor" : "none"} />{metadata.retained ? "保持を解除" : "保持する"}</button></Form><Form method="post" onSubmit={event => { if (!window.confirm("このメールを削除しますか？ この操作は取り消せません。")) event.preventDefault(); }}><input type="hidden" name="intent" value="delete" /><button className="icon-button" aria-label="メールを削除" title="メールを削除"><Trash2 size={18} /></button></Form></div></header><article className="mail-detail"><div className="message-avatar">{metadata.from.charAt(0).toUpperCase()}</div><div className="detail-heading"><h1>{metadata.subject || "(件名なし)"}</h1><p><b>{metadata.from}</b> <span>→ {metadata.to}</span></p><time>{new Date(metadata.timestamp).toLocaleString("ja-JP")}</time></div><MailContent raw={raw} /></article></section></Shell>; }
